name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install server dependencies
      run: npm install
    - name: Install dependencies, update snapshots and run tests
      working-directory: ./client
      run: |
        npm install
        npm run test -- -u
